swagger: "2.0"
info:
  description: The swagger file
  version: "1.0.0"
  title: REST API Machine Problem
consumes:
  - application/json
produces:
  - application/json

basePath: /api

paths:
  /jobs:
    get:
      operationId: views.read_job_all
      tags:
        - Jobs
      summary: Read the entire list of jobs
      description: Read the list of jobs
      responses:
        200:
          description: Successfully read jobs list operation
          schema:
            type: array
            items:
              properties:
                job_id:
                  type: string
                app_name:
                  type: string
                state:
                  type: string
                timestamp:
                  type: string
    post:
      operationId: views.create_job
      tags:
        - Jobs
      summary: Create a new job
      description: Create a new job
      parameters:
        - name: job
          in: body
          description: Job to create
          required: True
          schema:
            type: object
            properties:
              job_id:
                type: string
              app_name:
                type: string
              state:
                type: string
      responses:
        201:
          description: Successfully created the job!

  /jobs/{job_id}:
    get:
      operationId: views.read_job
      tags:
        - Jobs
      summary: Read one job
      description: Read one job
      parameters:
        - name: job_id
          in: path
          description: The job id to search
          type: string
          required: True
      responses:
        200:
          description: Success!
          schema:
            properties:
              job_id:
                type: string
              app_name:
                type: string
              state:
                type: string
              timestamp:
                type: string

    put:
      operationId: views.update_job
      tags:
        - Jobs
      summary: Update a job
      description: Update a job
      parameters:
        - name: job_id
          in: path
          description: The Job id
          type: string
          required: True
        - name: job
          in: body
          schema:
            type: object
            properties:
              app_name:
                type: string
              state:
                type: string
      responses:
        200:
          description: Update Success!

    delete:
      operationId: views.delete_job
      tags:
        - Jobs
      summary: Delete a job
      description: Delete a job
      parameters:
        - name: job_id
          in: path
          type: string
          required: True
      responses:
        200:
          description: Delete Success!


